
###

DELETE http://localhost:5050/orders/
Content-Type: application/json

{
    "id":2,
    "userId":7
}



###

GET http://localhost:5050/orders/

###

PUT http://localhost:5050/orders/status/
Content-Type: application/json

{
    "id":5,
    "status":"On the Way"
}
